- name: Add PPA for certbot
  apt_repository:
    repo: ppa:certbot/certbot

- name: Install nginx and certbot
  apt:
    name:
      - nginx
      - python-certbot-nginx
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: Configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove default site from sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove default site from sites-available
  file:
    path: /etc/nginx/sites-available/default
    state: absent
