version: '3'

volumes:
  postgres_data: {}

services:

  django:
    build: .
    image: confsched_django
    depends_on:
      - postgres
    env_file:
      - .env/django.env
      - .env/postgres.env
    ports:
      - 8000:8000
    volumes:
      - .:/opt/confsched/

  postgres:
    image: postgres:10.5
    env_file:
      - .env/postgres.env
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data

  maildev:
    image: "djfarrelly/maildev:latest"
    command: >
      bin/maildev
      --web 80
      --smtp 25
      --incoming-user smtp@example.com
      --incoming-pass hunter2
    ports:
      - "1080:80"
