- name: Deploy application
  include_tasks: deploy.yml
  when: deploy

- name: Request SSL key
  command:
    cmd: >
      certbot --nginx certonly
      --non-interactive
      --agree-tos -m {{ admin_email }}
      --domain {{ host_name }}
    creates: "/etc/letsencrypt/live/{{ host_name }}/fullchain.pem"

- name: Template site-prod
  template:
    src: site-prod
    dest: "/etc/nginx/sites-available/site-{{ instance_name }}"
  notify:
    - Restart nginx

- name: Enable site-prod
  file:
    src: "/etc/nginx/sites-available/site-{{ instance_name }}"
    dest: "/etc/nginx/sites-enabled/site-{{ instance_name }}"
    state: link
  notify:
    - Restart nginx
