- name: Create DB user
  become: yes
  become_user: postgres
  postgresql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    role_attr_flags: "LOGIN"

- name: Create database
  become: yes
  become_user: postgres
  postgresql_db:
    name: "{{ db_name }}"

- name: Configure backups
  include_tasks: backup.yml
  when: backup