- name: Install nginx
  apt:
    state: present
    name: nginx
    update_cache: yes
    cache_valid_time: 3600

- include: app.yml

- name: Configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: Remove default site from sites-enabled
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Remove default site from sites-available
  file:
    path: /etc/nginx/sites-available/default
    state: absent

- name: Template site-prod
  template:
    src: site-prod
    dest: /etc/nginx/sites-available/site-prod
  notify:
    - Restart nginx

- name: Enable site-prod
  file:
    src: /etc/nginx/sites-available/site-prod
    dest: /etc/nginx/sites-enabled/site-prod
    state: link
  notify:
    - Restart nginx

- name: Collect static files
  django_manage:
    app_path: "{{ app_dir }}"
    command: collectstatic
    virtualenv: "{{ venv_dir }}"
    settings: "confsched.settings.base"

- name: Migrate database
  environment:
    POSTGRES_HOST: localhost
    POSTGRES_USER: "{{ db_user }}"
    POSTGRES_DB: "{{ db_name }}"
    POSTGRES_PASSWORD: "{{ db_password }}"
  django_manage:
    app_path: "{{ app_dir }}"
    command: migrate
    virtualenv: "{{ venv_dir }}"
    settings: "confsched.settings.db"
