# Generated by Django 2.1.1 on 2018-10-01 17:51

from django.conf import settings
import django.contrib.postgres.fields.ranges
from django.db import migrations, models
import django.db.models.deletion
import scheduler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('timezone', models.CharField(max_length=100, validators=[scheduler.models.validate_timezone])),
            ],
        ),
        migrations.CreateModel(
            name='ExpoDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expo_time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('lunch_time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Event')),
            ],
        ),
        migrations.CreateModel(
            name='ExpoDemand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(verbose_name='The amount of staffers needed in this time range')),
                ('time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.ExpoDay')),
            ],
        ),
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TALK', 'Attend talk'), ('LUNCH', 'Have lunch'), ('BOOTH_DUTY', 'Booth duty'), ('FREE', 'Free time')], max_length=300)),
                ('time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('current', models.BooleanField(verbose_name='Whether this is a current or a historical schedule entry')),
                ('final', models.BooleanField(verbose_name='Whether this schedule entry may be changed in the future')),
                ('created', models.DateTimeField(verbose_name='The time this schedule entry was created')),
            ],
        ),
        migrations.CreateModel(
            name='Staffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TalkLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('travel_distance', models.IntegerField(verbose_name='The time to travel from the booth to/from this location, in minutes')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Event')),
            ],
        ),
        migrations.CreateModel(
            name='TalkRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('time', django.contrib.postgres.fields.ranges.DateTimeRangeField()),
                ('priority', models.IntegerField(verbose_name='Lowest number has the highest priority. Only the rank matters.')),
                ('staffer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Staffer')),
                ('talk_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.TalkLocation')),
            ],
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='staffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Staffer'),
        ),
        migrations.AddField(
            model_name='scheduleentry',
            name='talk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='scheduler.TalkRequest'),
        ),
        migrations.AddField(
            model_name='availability',
            name='staffer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Staffer'),
        ),
    ]
