# Generated by Django 2.1.1 on 2018-10-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20181008_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='slug',
            field=models.CharField(db_index=True, default='reinvent', max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
