# Generated by Django 2.1.1 on 2018-10-08 16:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('scheduler', '0002_auto_20181008_1646'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='staffer',
            unique_together={('user', 'event')},
        ),
    ]
